- name: Install Nginx
  hosts: all

  tasks:
    - name: update
      apt: update_cache=yes

    - name: Install Nginx
      apt: name=nginx state="{{ nginx_version }}"
      debug:
        msg: "Nginx version is {{ nginx_version }}"

- name: Start Nginx
  hosts: all
  tasks:
    - name: Check status Nginx
      ansible.builtin.service:
        name: nginx
        state: started
      