services:
  awx:
    image: quay.io/ansible/awx
    container_name: awx
    ports:
      - "80:8052"       # Map AWX's default HTTP port
      - "443:8053"      # Map AWX's default HTTPS port
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: awx-postgres
    environment:
      POSTGRES_USER: awx
      POSTGRES_PASSWORD: awxpass
      POSTGRES_DB: awx
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
